---
# .ansible-lint
# Source: https://ansible.readthedocs.io/projects/lint/configuring/#ansible-lint-configuration

profile: basic
exclude_paths:
  - .cache/ # implicit unless exclude_paths is defined in config
  - test/fixtures/formatting-before/
  - test/fixtures/formatting-prettier/
  - collections/ansible_collections/
  - collections/nokia/
  - collections/vyos/


# Mock modules or roles in order to pass ansible-playbook --syntax-check
mock_modules:
  - zuul_return
  # note the foo.bar is invalid as being neither a module or a collection
  - fake_namespace.fake_collection.fake_module
  - fake_namespace.fake_collection.fake_module.fake_submodule
mock_roles:
  - mocked_role
  - author.role_name # old standalone galaxy role
  - fake_namespace.fake_collection.fake_role # role within a collection

loop_var_prefix: "^(__|{role}_)"

var_naming_pattern: "^[a-z_][a-z0-9_]*$"

use_default_rules: true

skip_list:
  - skip_this_tag

enable_list:
  - args
  - empty-string-compare # opt-in
  - no-log-password # opt-in
  - no-same-owner # opt-in
  - name[prefix] # opt-in
  - galaxy-version-incorrect # opt-in
  - yaml

warn_list:
  - skip_this_tag
  - experimental

offline: true

extra_vars:
  foo: bar
  multiline_string_variable: |
    line1
    line2
  complex_variable: ":{;\t$()"

kinds:
  - yaml: "**/*.yaml-too"

task_name_prefix: "{stem} | "
