download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/vyos-vyos-6.0.0.tar.gz
format_version: 1.0.0
name: vyos
namespace: vyos
server: https://galaxy.ansible.com/api/
signatures: []
version: 6.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/vyos/vyos/versions/6.0.0/
