name: ansible-lint
on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c .ansible-lint.yml -v"
          setup_python: "true"
          working_directory: ""
          requirements_file: "playbooks/collections/requirements.yml"
